version: '2'
services:
    plataforma-app:
        image: plataforma
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://plataforma-mysql:3306/plataforma?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://plataforma-elasticsearch:9200
        ports:
            - 8080:8080
    plataforma-mysql:
        extends:
            file: mysql.yml
            service: plataforma-mysql
    plataforma-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: plataforma-elasticsearch
